server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service-id
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost